### ISSUE TITLE
Plugin redundant?

### ISSUE THREAD

**Issue by awilderink** [TotalTechGeek/elysia-lambda#3]
With the `bun` runtime on AWS already transforming the Gateway request to a native `Request`, isn't it just easier to use `app.handle(request)`?

```ts
// lambda.ts
import { Elysia } from "elysia";

const app = new Elysia()
  .get("/", () => {
    return new Response("Hello World!")
  });

export default {
  fetch(request: Request) {
    return app.handle(request);
  }
}
```

Please correct me if I'm wrong.

**Comment by TotalTechGeek** [comment]
Hey!

Most of the code for the plugin isn't for setting up that touch point, although this signature has changed a few times between editions of Elysia. 

```
export default {
  fetch(request: Request) {
    return app.handle(request);
  }
}
```

Most of the plugin's code (and there isn't much of it) is set up around making it easier for users to set up the custom layer and perform some simple deployments.

It's also meant to stay out of your way when you're not deployed on Lambda, so that you can run your code locally / package it into containers without needing to change anything.

**Comment by sandys** [comment]
> It's also meant to stay out of your way when you're not deployed on Lambda, so that you can run your code locally / package it into containers without needing to change anything.

@TotalTechGeek sorry to reply to an older thread, but can u mention how to use this plugin and get both options:
1. package into docker containers for local running
2. aws lambda deploy
